version: '2'
services:
    govideo:
        image: gongluck/govideo_server
        container_name: govideo
        hostname: govideo
        network_mode: bridge
        command: /govideo_server/app
        volumes: 
            - ./videos:/govideo_server/videos
            - ./database:/govideo_server/database
        ports:
            - "80:80"
        depends_on:
            - redis
        links:
            - redis:redis
        
    redis:
        image: redis
        container_name: redis
        hostname: redis
        network_mode: bridge
        command: redis-server
        restart: always
